//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.02.22 at 01:32:54 PM CET
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/message/")
package main.java.com.ubo.tp.message.datamodel.jaxb.bean.user;
